update scripts

diff --git a/src/scripts/installer b/src/scripts/installer
--- a/src/scripts/installer
+++ b/src/scripts/installer
@@ -1,13 +1,17 @@
 #!/bin/sh
 
+# DSM 5 -> 7 upgrade path:
+# - Not supported
+# DSM 6 -> 7 upgrade path:
+# - files are migrated from ${SYNOPKG_PKGDEST}/var to ${SYNOPKG_PKGVAR}
+
 # installer log is not writable, use for reference only.
 INST_LOG="/var/log/packages/${SYNOPKG_PKGNAME}.log"
 
-# Old files from config directory, before ver. 1.2.125.
-OLD_FWPORTS="${SYNOPKG_PKGDEST}/config/${SYNOPKG_PKGNAME}.sc"
-OLD_LOG="${SYNOPKG_PKGDEST}/config/${SYNOPKG_PKGNAME}.log"
+# Optional FWPORTS file
+FWPORTS_FILE="/var/packages/${SYNOPKG_PKGNAME}/conf/${SYNOPKG_PKGNAME}.sc"
 
-# Temporary directory when the package is upgrading.
+# Temporary directory when the package is upgrading
 TMP_DIR="${SYNOPKG_TEMP_UPGRADE_FOLDER}"
 
 install_log ()
@@ -73,6 +77,34 @@ call_func "initialize_variables"
 
 ### Functions library
 
+#
+# syncronize all files from var folder in spk (extracted to target/var)
+# (@appdata) /var/packages/<package>/target/var -> /var/packages/<package>/var
+#
+syno_sync_var_folder () {
+    # take all files that do not alredy exist and rename the other files to *.new to avoid overwriting
+    # existing configuration files.
+    # finally remove the target/var folder that is not used under DSM 7.
+    if [ -d ${SYNOPKG_PKGDEST}/var -a "$(ls -A ${SYNOPKG_PKGDEST}/var 2>/dev/null)" ]; then
+    
+        echo "Install files from var folder"
+    
+        # Move all files except existing
+        echo "$RSYNC --ignore-existing --remove-source-files ${SYNOPKG_PKGDEST}/var/ ${SYNOPKG_PKGVAR}"
+        $RSYNC --ignore-existing --remove-source-files ${SYNOPKG_PKGDEST}/var/ ${SYNOPKG_PKGVAR}
+
+        # Rename any remaining (thus pre-existing) files with .new suffix
+        find ${SYNOPKG_PKGDEST}/var -type f -exec sh -c 'x="{}"; mv "$x" "${x}.new"' \;
+
+        # Move .new files (overwrite existing)
+        echo "$RSYNC --remove-source-files ${SYNOPKG_PKGDEST}/var/ ${SYNOPKG_PKGVAR}"
+        $RSYNC --remove-source-files ${SYNOPKG_PKGDEST}/var/ ${SYNOPKG_PKGVAR}
+
+        # Remove var folder extraced from spk
+        $RM ${SYNOPKG_PKGDEST}/var
+    fi
+}
+
 set_unix_permissions ()
 {
     echo "Notice: set_unix_permissions() is no longer required on DSM7."
@@ -116,6 +148,14 @@ preinst ()
     call_func "validate_preinst"
     call_func "service_preinst" install_log
 
+    # Check volume exists
+    if [ -n "${SHARE_PATH}" ]; then
+        if [ ! -d "${SHARE_VOLUME}" ]; then
+            echo "ERROR: Volume ${SHARE_VOLUME} does not exist." | $TEE 1>&2
+            exit 1
+        fi
+    fi
+
     exit 0
 }
 
@@ -124,16 +164,9 @@ postinst ()
     log_step "postinst"
     call_func "save_wizard_variables" install_log
 
-    if [ "${wizard_enable_aut}" == "false" ]; then
-       exit 0
-    else
-       echo "{" >> ${SYNOPKG_PKGDEST}/config/accs.db
-       echo '"@user@":"@password@"' >> ${SYNOPKG_PKGDEST}/config/accs.db
-       echo "}" >> ${SYNOPKG_PKGDEST}/config/accs.db
-
-       sed -i -e "s|@user@|${wizard_username:=admin}|g" ${SYNOPKG_PKGDEST}/config/accs.db
-       sed -i -e "s|@password@|${wizard_password:=admin}|g" ${SYNOPKG_PKGDEST}/config/accs.db
-    fi
+    # copy target/var data to permanent storage
+    # and don't override old configurations
+    call_func "syno_sync_var_folder" install_log
 
     call_func "service_postinst" install_log
 
@@ -179,20 +212,19 @@ preupgrade ()
     log_step "preupgrade"
     call_func "validate_preupgrade"
 
-    # Copy config files
-    if [ -d ${SYNOPKG_PKGDEST}/config -a "$(ls -A ${SYNOPKG_PKGDEST}/config 2>/dev/null)" ]; then
-        #Removing old files used before ver. 1.2.125
-        if [ -r "${OLD_FWPORTS}" ]; then
-           $RM ${OLD_FWPORTS} | install_log
+    # dsm6 -> dsm7
+    if [ -d ${SYNOPKG_PKGDEST}/var ]; then
+        if [ ! -d ${SYNOPKG_PKGVAR} -o $(realpath ${SYNOPKG_PKGVAR}) = $(realpath ${SYNOPKG_PKGDEST}/var) ]; then
+            # Copy to temporary directory if upgrading from DSM6 -> DSM7
+            # Then restore once to permanent storage at postupgrade
+            if [ -d ${SYNOPKG_PKGDEST}/var -a "$(ls -A ${SYNOPKG_PKGDEST}/var 2>/dev/null)" ]; then
+                echo "Backup target/var folder used under DSM6" | install_log
+                echo "$RSYNC ${SYNOPKG_PKGDEST}/var/ ${TMP_DIR}" | install_log
+                $RSYNC ${SYNOPKG_PKGDEST}/var/ ${TMP_DIR} 2>&1 | install_log
+                # remove DSM6 target/var folder
+                rm -rf ${SYNOPKG_PKGDEST}/var 2>&1 | install_log
+            fi
         fi
-
-        if [ -r "${OLD_LOG}" ]; then
-           $RM ${OLD_LOG} | install_log
-        fi
-        # Copy config files to temporary directory
-           echo "Backup target/config folder" | install_log
-           echo "$RSYNC ${SYNOPKG_PKGDEST}/config/ ${TMP_DIR}" | install_log
-           $RSYNC ${SYNOPKG_PKGDEST}/config ${TMP_DIR} 2>&1 | install_log
     fi
 
     call_func "service_preupgrade" install_log
@@ -203,17 +235,19 @@ preupgrade ()
 postupgrade ()
 {
     log_step "postupgrade"
+
     call_func "service_restore" install_log
 
-    # Restore config files
+    # dsm6 -> dsm7
     if [ -d ${TMP_DIR} -a "$(ls -A ${TMP_DIR} 2>/dev/null)" ]; then
-        # Restore once at postupgrade
-        echo "Resore config folder" | install_log
+        # Restore once to permanent storage at postupgrade
+        echo "Resore var folder from DSM6" | install_log
         echo "$RSYNC ${TMP_DIR}/ ${SYNOPKG_PKGVAR}" | install_log
-        $RM ${SYNOPKG_PKGDEST}/config 2>&1 | install_log
-        $RSYNC ${TMP_DIR}/ ${SYNOPKG_PKGDEST} 2>&1 | install_log
+        $RSYNC ${TMP_DIR}/ ${SYNOPKG_PKGVAR} 2>&1 | install_log
     fi
 
+    # dsm7: Now sync in any new files to permanent storage
+    call_func "syno_sync_var_folder" install_log
     call_func "service_postupgrade" install_log
 
     exit 0
